services:
  # A Docker web service
  - type: web
    name: api
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    envVars:
      - key: DB_URL
        fromDatabase:
          name: test
          property: connectionString
  - type: web
    name: web client
    rootDir: client
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_HOST
        fromService:
          name: api
          type: web
          property: host

databases:
  # db 1
  - name: test
    region: frankfurt
    plan: free
    user: gorm
